import LegalPage from "./LegalPage";

const TERMS_CONTENT_EN = `Please read these terms carefully before using the SDKCraft platform ("the Platform"), owned and operated by BMS ("we", "the Company"). By using the Platform, you agree to be bound by these terms.

## 1. Description of Service
SDKCraft is a platform that allows you to upload API specification files (in OpenAPI/Swagger format) to automatically generate software development kits (SDKs) in multiple programming languages, along with supporting features such as detecting changes between two versions of the same API and AI-assisted documentation generation.

## 2. Account and Registration
Use of certain Platform features requires signing in via a GitHub account. You are responsible for maintaining the confidentiality of your account credentials and for any activity conducted through it.

## 3. Acceptable Use
You may use the Platform only for legitimate software-development purposes. You may not:
- Attempt to circumvent the usage limits (rate limits) imposed on the free tier by any technical means (such as creating multiple accounts or using network proxies/VPNs for this specific purpose).
- Use the Platform for any unlawful purpose or to generate code intended to harm other systems.
- Attempt unauthorized access to our systems or databases, or call our APIs from unauthorized domains.
- Resell access to the Platform without our prior written consent.

## 4. Free and Paid Plans
The Platform currently offers a free usage tier with defined daily limits (SDK generation, documentation generation, batch uploads, change detection). **Note: the paid plans shown on the pricing page are currently being finalized from a technical standpoint, and no charges are being processed until they are officially activated.** Users will be clearly notified once paid billing is activated and subscriptions begin to apply.

## 5. Content You Upload
You are solely responsible for the content of the API files you upload to the Platform. You represent that you have the legal right to upload and process this content. We claim no ownership over your API specifications or the code generated from them â€” the resulting SDK output is entirely yours.

**Note regarding the AI feature:** when you use the AI-powered documentation feature, the content of your file is sent to a third-party AI provider for processing. Do not use this feature with API specifications containing confidential or sensitive information you do not wish to share with a third party.

## 6. Disclaimer Regarding Generated Code
We make reasonable efforts to ensure the quality of generated SDKs, but **we do not guarantee they are entirely free of errors or fully suited to every use case**. You are responsible for reviewing and testing any generated code before using it in a production environment. We are not liable for any direct or indirect damages arising from the use of code generated by the Platform.

## 7. Service Availability
We strive to keep the Platform continuously available, but we do not guarantee 100% uptime at all times, and the service may be subject to maintenance windows or unplanned interruptions.

## 8. Account Termination
We reserve the right to suspend or terminate your access to the Platform if you violate these terms, particularly in cases of abuse or attempts to circumvent free-tier usage limits.

## 9. Changes to the Service and These Terms
We reserve the right to modify Platform features or these terms at any time. The "last updated" date at the top of this page will reflect the most recent revision, and continued use of the Platform after any such change constitutes acceptance of it.

## 10. Governing Law and Dispute Resolution
These terms are governed by and construed in accordance with the laws of Libya, and any dispute arising from them shall be subject to the exclusive jurisdiction of the competent Libyan courts.

## 11. Contact Us
For any questions regarding these terms, contact us at:
**[ihsan.elashhab@gmail.com]**`;

export default function TermsOfService() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="[DATE]"
      content={TERMS_CONTENT_EN}
      lang="en"
      altLangHref="/terms/ar"
      altLangLabel="Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©"
    />
  );
}
